import { i18n, t } from "@/i18n";

/** Translate known product enum labels without changing their persisted IDs.
 * Unknown values belong to extension providers or user configuration and are
 * preserved. A role domain resolves titles that overlap generic status words.
 */
const commonLabels: Record<string, string> = {
  "planned": "Planned",
  "shared": "Shared",
  "ephemeral": "Ephemeral",
  "cleanup_pending": "Cleanup pending",
  "rate_limited": "Rate limited",
  "schedule": "Schedule",
  "bearer": "Bearer token",
  "hmac_sha256": "HMAC-SHA256",
  "github_hmac": "GitHub HMAC",
  "in_queue": "In queue",
  "merged": "Merged",
  "synced": "Synced",
  "sync_pending": "Sync pending",
  "sync_failed": "Sync failed",
  "out_of_sync": "Out of sync",
  "unavailable": "Unavailable",
  "suspended": "Suspended",
  "revision_requested": "Revision requested",
  "cleanup_failed": "Cleanup failed",
  "coming_soon": "Coming soon",
  "quarantined": "Quarantined",
  "changes_requested": "Changes requested",
  "abandoned": "Abandoned",
  "accepted_with_notes": "Accepted with notes",
  "entered_query": "Entered query",
  "left_query": "Left query",
  "updated": "Updated",
  "field_changed": "Field changed",
  "status_changed": "Status changed",
  "created": "Created",
  "assignment": "Assignment",
  "timer": "Timer",
  "on_demand": "On demand",
  "api": "API",
  "cron": "Cron",
  "webhook": "Webhook",
  "callback": "Callback",
  "signal": "Signal",
  "startup": "Startup",
  "message": "Message",
  "retry": "Retry",
  "recovery": "Recovery",
  "dispatch": "Dispatch",
  "draft_config": "Draft configuration",
  "deployment": "Deployment",
  "ticket": "Ticket",
  "lead": "Lead",
  "object": "Object",
  "document": "Document",
  "plan": "Plan",
  "summary": "Summary",
  "notes": "Notes",
  "report": "Report",
  "spec": "Specification",
  "specification": "Specification",
  "proposal": "Proposal",
  "review": "Review",
  "open": "Open",
  "working": "Working",
  "ssh": "SSH",
  "sandbox": "Sandbox",
  "http": "HTTP",
  "local_trusted": "Local trusted",
  "authenticated": "Authenticated",
  "bootstrap_ceo": "Bootstrap CEO",
  "agents_only": "Agents only",
  "humans_only": "Humans only",
  "both": "Both",
  "explicit": "Explicit",
  "pattern": "Pattern",
  "default": "Default",
  "tool": "Tool",
  "connection": "Connection",
  "application": "Application",
  "risk": "Risk",
  "read_only": "Read only",
  "read_write": "Read and write",
  "destructive": "Destructive",
  "off": "Off",
  "on": "On",
  "reconnected": "Reconnected",
  "new": "New",
  "snapshot": "Snapshot",
  "backup": "Backup",
  "restore": "Restore",
  "migrate": "Migrate",
  "validate": "Validate",
  "starting": "Starting",
  "stopping": "Stopping",
  "backlog": "Backlog",
  "todo": "To do",
  "in_progress": "In progress",
  "in_review": "In review",
  "done": "Done",
  "blocked": "Blocked",
  "cancelled": "Cancelled",
  "canceled": "Canceled",
  "pending": "Pending",
  "approved": "Approved",
  "rejected": "Rejected",
  "accepted": "Accepted",
  "skipped": "Skipped",
  "expired": "Expired",
  "withdrawn": "Withdrawn",
  "queued": "Queued",
  "running": "Running",
  "succeeded": "Succeeded",
  "failed": "Failed",
  "timed_out": "Timed out",
  "scheduled_retry": "Scheduled retry",
  "paused": "Paused",
  "idle": "Idle",
  "active": "Active",
  "error": "Error",
  "terminated": "Terminated",
  "draft": "Draft",
  "ready": "Ready",
  "loading": "Loading",
  "archived": "Archived",
  "deleted": "Deleted",
  "unknown": "Unknown",
  "none": "None",
  "unassigned": "Unassigned",
  "critical": "Critical",
  "high": "High",
  "medium": "Medium",
  "low": "Low",
  "agent": "Agent",
  "user": "User",
  "human": "Human",
  "board": "Board",
  "system": "System",
  "company": "Company",
  "organization": "Organization",
  "project": "Project",
  "issue": "Issue",
  "task": "Task",
  "goal": "Goal",
  "routine": "Routine",
  "workspace": "Workspace",
  "worktree": "Worktree",
  "approval": "Approval",
  "run": "Run",
  "heartbeat": "Heartbeat",
  "secret": "Secret",
  "admin": "Admin",
  "member": "Member",
  "owner": "Owner",
  "viewer": "Viewer",
  "instance_admin": "Instance admin",
  "local_board": "Local board",
  "invited": "Invited",
  "joined": "Joined",
  "left": "Left",
  "enabled": "Enabled",
  "disabled": "Disabled",
  "connected": "Connected",
  "disconnected": "Disconnected",
  "auth_required": "Authentication required",
  "unreachable": "Unreachable",
  "fresh": "Fresh",
  "stale": "Stale",
  "missing": "Missing",
  "granted": "Granted",
  "denied": "Denied",
  "revoked": "Revoked",
  "allow": "Allow",
  "deny": "Deny",
  "read": "Read",
  "write": "Write",
  "manage": "Manage",
  "completed": "Completed",
  "not_run": "Not run",
  "interrupted": "Interrupted",
  "scheduled": "Scheduled",
  "triggered": "Triggered",
  "cleared": "Cleared",
  "warning": "Warning",
  "info": "Info",
  "success": "Success",
  "neutral": "Neutral",
  "danger": "Danger",
  "standard": "Standard",
  "ask": "Ask",
  "planning": "Planning",
  "skill_test": "Skill test",
  "process": "Process",
  "local": "Local",
  "remote": "Remote",
  "cloud": "Cloud",
  "private": "Private",
  "public": "Public",
  "manual": "Manual",
  "automatic": "Automatic",
  "validating": "Validating",
  "degraded": "Degraded",
  "healthy": "Healthy",
  "repairing": "Repairing",
  "provisioning": "Provisioning",
  "cloning": "Cloning",
  "seeded": "Seeded",
  "awaiting_approval": "Awaiting approval",
  "pending_approval": "Pending approval",
  "not_creator": "Anyone else",
  "human_only": "Human only",
  "anyone": "Anyone",
  "coalesced": "Coalesced",
  "superseded": "Superseded",
  "hold": "Hold",
  "waiting": "Waiting",
  "stopped": "Stopped",
  "not_started": "Not started",
  "retrying": "Retrying",
  "syncing": "Syncing",
  "requested": "Requested",
  "assignee": "Assignee",
  "reviewer": "Reviewer",
  "approver": "Approver"
};
const roleLabels: Record<string, string> = {
  "ceo": "CEO",
  "cto": "CTO",
  "cmo": "CMO",
  "cfo": "CFO",
  "security": "Security",
  "engineer": "Engineer",
  "designer": "Designer",
  "pm": "PM",
  "qa": "QA",
  "devops": "DevOps",
  "researcher": "Researcher",
  "general": "General"
};

export function getDisplayLabel(value: string | null | undefined, domain?: string): string {
  if (value == null || value === "") return t("zhSupport.labels.common.none");
  if (domain === "raw" && (i18n.resolvedLanguage ?? i18n.language).startsWith("en")) return value;
  const id = value.trim().replace(/([a-z0-9])([A-Z])/g, "$1_$2").replace(/[\s-]+/g, "_").toLowerCase();
  const isRole = domain === "role" || domain === "agentRole" || domain === "agent_role";
  if (isRole && Object.hasOwn(roleLabels, id)) {
    return t(`zhSupport.labels.role.${id}`, { defaultValue: roleLabels[id] });
  }
  if (Object.hasOwn(commonLabels, id)) {
    return t(`zhSupport.labels.common.${id}`, { defaultValue: commonLabels[id] });
  }
  return value;
}
